TrainingInstitutePackage/main/default/objects/Account/fields/Total_Order__c.field-meta.xml
<CustomField>
    <fullName>Total_Order__c</fullName>
    <label>Total Order</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

TrainingInstitutePackage/main/default/objects/Order/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

TrainingInstitutePackage/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrainingInstitutePackage/main/default/objects/Trainer__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Trainers</relationshipLabel>
    <relationshipName>Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

TrainingInstitutePackage/main/default/classes/WebController.cls
public with sharing class WebController {
    public WebController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Account> GetAccountList(){
    try {
        System.Debug('I am here Account');
        List<Account> accList =[select Id, name, description, Rating, Total_Order__c from Account WHERE Total_Order__c > 0 ORDER BY Total_Order__c DESC LIMIT 4];
        return accList;

        } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Product2> GetProductList(){
    try {
        System.Debug('I am here Product2');
        List<Product2> prdList =[select Id, name, description, Family from Product2 WHERE Family != '' LIMIT 4];
        return prdList;

        } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Product2> GetProductByName(String productName){
    try {
        System.Debug('I am here GetProductByName');
        String nameLike = '%'+ productName +'%';
        List<Product2> prdList =[select Id, name, description, Family from Product2 where name LIKE : nameLike AND Family != '' LIMIT 10];
        return prdList;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    
    }

    @AuraEnabled(cacheable=true)
    public static PriceBookEntry GetPriceForProduct(String productId){
    try {
        System.Debug('I am here GetPriceForProduct');
        PriceBookEntry prdPrice =[select Id, Product2Id, UnitPrice from PricebookEntry where Product2Id = :productId And Pricebook2Id in (select Id from Pricebook2 where Name <> 'Standard Price Book') LIMIT 1];
        return prdPrice;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Trainer__c GetTrainerDetails(String productId){
    try {
        System.Debug('I am here GetTrainerDetails');
        Trainer__c trainerDetail =[select Id, Name, Product__c FROM Trainer__c WHERE Product__c = :productId LIMIT 1];
        return trainerDetail;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}